/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/core/mat.hpp>
#include <android/log.h>
/* Header for class com_example_bcmanager_MainActivity */

#ifndef _Included_com_example_bcmanager_MainActivity
#define _Included_com_example_bcmanager_MainActivity
#ifdef __cplusplus

#define LOG_TAG "TAG"
#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, LOG_TAG, __VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG , LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO , LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN , LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR , LOG_TAG, __VA_ARGS__)


extern "C" {
#endif
#undef com_example_bcmanager_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_bcmanager_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_bcmanager_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_bcmanager_CameraActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);
JNIEXPORT void JNICALL Java_com_example_bcmanager_MainActivity_RecognitionCard(JNIEnv *env, jobject thiz, jlong input_image,
                                                                         jlong output_image);

#ifdef __cplusplus
}
#endif
#endif
